### ISSUE TITLE
【/cart】UI調整

### ISSUE THREAD

**Issue by ryoto-oguma** [immersive-bootcamp-Squirtle/MenuCare#111]

**Comment by emap-strawberry** [comment]
`frontend\user\src\components\ProductModal\ProductModal.jsx`
- モーダルを立ち上げたときに背景のグレーも下からスライドアップしていたのを修正
- 価格のフォントサイズを変更(文字は小さく、金額は大きく)
- 商品名のフォントサイズを変更

**Comment by emap-strawberry** [comment]
`frontend\user\src\pages\Cart\cart.jsx`
- CartSummaryとCartActionsを画面下部に固定しCartItemがそれをはみ出る場合はスクロールできるように
`frontend\user\src\components\CartItem\CartItem.jsx`
- 文字サイズの調整、一部中央寄せ→左寄せに
`frontend\user\src\components\CartSummary\CartSummary.jsx`
- 文字サイズの調整、下部に固定
`frontend\user\src\components\CartActions\CartActions.jsx`
- ボタンカラーとサイズの調整
