### ISSUE TITLE
【/menu】UI微調整

### ISSUE THREAD

**Issue by ryoto-oguma** [immersive-bootcamp-Squirtle/MenuCare#58]
【Todo】
・「アレルギーあり」に▽つけてモーダルが展開されることをわかりやすくする
・フィルタを中央寄せに
・上の各種ボタンを中央寄せ or 別の項目を作って横スクロールされるように
・余白を入れる
・PCサイズにしたときに崩れるのを治したい
・データ読み込み時に背景が黒くなるのを直したい

**Comment by emap-strawberry** [comment]
`frontend\user\src\components\Menu\NavBar.jsx`
- 「アレルギーあり」に▽つけてモーダルが展開されることをわかりやすくする
- フィルタを中央寄せに
- 上の各種ボタンを中央寄せ or 別の項目を作って横スクロールされるように
- 【＋α】「メニュー一覧」が左寄せになってたので中央に直した

`frontend\user\src\components\Menu\MenuList.jsx`
- 余白を入れる
- PCサイズにしたときに崩れるのを治したい

`frontend\user\src\components\Menu\MenuItem.jsx`
- 【＋α】上記レイアウト変更に伴う微調整

`frontend\user\src\components\allergyFilterModal\allergyFilterModal.jsx`
- 【＋α】モーダルの幅、絞り込みボタンのスタイル調整
