### ISSUE TITLE
画像アップロード＆ダウンロード方式

### ISSUE THREAD

**Issue by ryoto-oguma** [immersive-bootcamp-Squirtle/MenuCare#72]
- upload
  - 画像データをformから受け取る
  - データを受け取り次第、jsが署名付きURL発行を目的としたAPIを投げる
  - APIレスポンスとして署名付きURLが返される
  - そのURLを使って、画像をアップロードする
  - 画像指定しない場合はデフォルト画像を設定する (DB上、image urlは必須とする)

- download
  - 画像ファイルのパスをitemから取り出す
  - 取り出した画像ファイルのパスをインプットに、対応するダウンロード用の署名付きURL発行を目的としたAPIを投げる
  - APIレスポンスとして署名付きURLが返される
  - そのURLを使って、画像をダウンロードする

- API側
  - APIリクエストを受け取り、対応する署名付きURLを発行する
  - 本来は権限制御等必要だが、後から追加するものとして省く ※ ex . 店舗AのQAからサイトを開いた人は、店舗Aが管理する画像しか見れない、というイメージ

**Comment by k-honda47** [comment]
## 実装案：

### 1. (Front) メニュー登録ボタン押下時に以下のデータをサーバーに送信:
- menu_name
- price
- アレルギー情報（IDリスト）
- 画像ファイル

⇛ axiosでAPIリクエストを実行

### 2. メニュー登録APIの処理フロー
- `POST /restaurants/:restaurant_id/menus`
- 2.2、2.3の登録処理は、#53 の方式に従う。

2.1 **画像アップロード**
   - リクエストの画像ファイル (`req.file`) をAWS S3に保存する。
   - S3から画像のURLを取得 (`image_url`)。
     - 署名付きURL？

2.2 **メニュー情報の登録**
   - 取得した `image_url` を使用

2.3 **アレルギー情報を中間テーブルに登録**
