### ISSUE TITLE
【構築】カート投入画面

### ISSUE THREAD

**Issue by ryoto-oguma** [immersive-bootcamp-Squirtle/MenuCare#81]

**Comment by t8-murakami** [comment]
・数量選択のUIが微妙
・カートに入れた後、リフレッシュすると注文確定と同じになる
・戻るボタン付けたい

**Comment by t8-murakami** [comment]
【課題】
リフレッシュすると、ポップアップが出て、カート情報がリセットされてしまう

**Comment by t8-murakami** [comment]
【残課題】
リロードすると、カート情報がリセットされてしまう
